### ISSUE TITLE
开学打卡

### ISSUE THREAD

**Issue by jackqwc** [FNDHSTD/WanxiaoHealthyCheckOnTencentCloud#3]
作者你好，最近陆续开始返校开学了，此代码开学后还可以继续使用吗？不可以的话会有开学打卡的版本吗？

**Comment by FNDHSTD** [comment]
返校后此项目会支持校内打卡，2.28号应该就可以使用校内打卡了

**Comment by ShawnRZ** [comment]
> 作者你好，最近陆续开始返校开学了，此代码开学后还可以继续使用吗？不可以的话会有开学打卡的版本吗？

等我返校后会支持校内打卡的，大概2.28就可以了吧

**Comment by jackqwc** [comment]
好的，感谢感谢

**Comment by StevenKim523** [comment]
作者你好，今天的打卡数据是获取的上次打卡数据吗？

**Comment by ShawnRZ** [comment]
> 作者你好，今天的打卡数据是获取的上次打卡数据吗？

是的

**Comment by ShawnRZ** [comment]
> 好的，感谢感谢

进度比较慢，主要这周有考试要准备，可能还要等几天
